spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/SD
spring.datasource.username=test_oop
spring.datasource.password=test_oop
spring.sql.init.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto = update
# show SQL queries
spring.jpa.show-sql=true
# set port
server.port=8081

